spring.application.name=ApiArteFrequencia
# CONFIGURAÇÕES DATABASE  

# DATABASE DB1
app.datasource.db1.jdbc-url=${DB1_URL}
app.datasource.db1.username=${DB1_USER}
app.datasource.db1.password=${DB1_PASS}
app.datasource.db1.driver-class-name=com.mysql.cj.jdbc.Driver

# DATABASE DB2
app.datasource.db2.jdbc-url=${DB2_URL}
app.datasource.db2.username=${DB2_USER}
app.datasource.db2.password=${DB2_PASS}
app.datasource.db2.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#porta do serviço
server.port=${PORT:8080}

# JWT TOKEN
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


